host: 120.55.184.211      # es host
port: 2015          # es port
username: mofang   # es username
password: bomeeniubi  # es password
mail:
  username: fuyi@23mofang.com
  password: xxx
  smtp_host: smtp.exmail.qq.com
  smtp_port: 25
  send_to:
    - fuyi@23mofang.com
  from_addr: fuyi@23mofang.com             # 显示发送出去的用户是谁
  reply_to: fuyi@23mofang.com              # 发送出去的邮件回复给谁
#  tpl_file: "/xx/xx/xx.tpl"         # go template模板文件     tpl_file与content必须存在一个
#  content: "xxx{{total}}xxxx"       # go template模板字符串
#  theme: "xxxx"                     # 邮件主题
rules:              # 检查规则
  - name: "test"   # 没有规则必须有一个唯一的name
    index: gateway-*  
    query:          # 查询条件，可以使任何符合 es规范的查询条件，我将转化为json字符串放入请求body想es发起请求
      exists:
        field: message.serviceException
    hits: 10        # 当符合条件大于多少条是进行报警
    interval:       # 隔多久发起一次请求，该字段会根据里面的语义信息转换时间
      second: 30
    time:           # 查询当前时间之前多久的数据，该字段会根据里面的语义信息转换时间
      hour: 1
    alerts:                                  # 报警
#      - type: http                          # http报警规则
#        url: http://baidu.com
      - type: mail                          # mail报警规则
        mail:                               # 该配置项参数与外层mail参数一致，该配置优先级高于外层mail配置
          tpl_file: tpl/test.tpl         # go template模板文件     tpl_file与content必须存在一个
#          content: "xxx{{total}}xxxx"       # go template模板字符串
          subject: esalert test                     # 邮件主题