host: locahost
port: 9200
username: elastic
password: changeme
rules:
  -
  index: gateway-*
  query:
    exists:
      field: message.serviceException
  hits: 10
  interval: 60
  alert:
    type: http

